# Generated by Django 3.0.3 on 2020-05-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='users',
        ),
    ]
